name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.3.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache PNPM Store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies for all layers
        run: |
          cd core && pnpm install --store ~/.pnpm-store
          cd ../hotels && pnpm install --store ~/.pnpm-store
          cd ../auth && pnpm install --store ~/.pnpm-store
          cd ../reservations && pnpm install --store ~/.pnpm-store
          cd ../app && pnpm install --store ~/.pnpm-store

  test:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        layer:
          - core
          - hotels
          - app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.3.0

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            core/node_modules
            hotels/node_modules
            app/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run tests for ${{ matrix.layer }}
        run: cd ${{ matrix.layer }} && pnpm test
